### ISSUE TITLE
SiwaveSimulationSettings seems to be broken

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#300] opened 2023-11-07 09:09 UTC
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

All properties from SiwaveSimulationSettings are not accesible.

### 📝 Steps to reproduce

![image](https://github.com/ansys/pyedb-core/assets/74993647/ddb58720-b62e-45cc-864b-e52308c29a41)

![image](https://github.com/ansys/pyedb-core/assets/74993647/2e73b5cb-c30f-4b22-9529-164d8cafe893)

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2024.1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-api-edb-v1 @ file:///C:/Users/svandenb/PycharmProjects/pyedb/protos
-e git+https://github.com/ansys/pyedb@08d794ee41ae3f4ca778e0fdc3c91b336f9b88ae#egg=ansys_edb
ansys-pythonnet==3.1.0rc2
cffi==1.16.0
clr-loader==0.2.6
colorama==0.4.6
e==1.4.5
exceptiongroup==1.1.3
grpcio==1.47.5
grpcio-tools==1.47.5
importlib-metadata==6.8.0
iniconfig==2.0.0
mock==5.1.0
numpy==1.26.0
packaging==23.2
pluggy==1.3.0
plumbum==1.8.2
protobuf==3.20.3
psutil==5.9.5
-e git+https://github.com/ansys-internal/pyansys-edb@523d46364a025a9f6a99f6c0c9f4e65e66096423#egg=pyansys_edb
pycparser==2.21
pytest==7.4.3
pywin32==306
rpyc==5.3.1
six==1.16.0
tomli==2.0.1
zipp==3.17.0
```

**Comment by drewm102** [comment] 2024-04-17 20:36
@svandenb-dev I am not able to reproduce this. I will close this out but feel free to reopen it if you can still reproduce it

**Closed by drewm102** 2024-04-17 20:36 UTC
Labels: bug
