### ISSUE TITLE
PadstackDefData(pin.data).get_pad_parameters() return errors if PadType is not defined

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb-core#316] opened 2023-11-14 08:45 UTC
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When we request pad parameters from PadstackDefData and there is no Pad defined the API returns an error. For instance

![image](https://github.com/ansys/pyedb-core/assets/74993647/41fd7bd1-3024-4522-9341-17e37d75a360)

but requesting antipad parameters thrown error. If no antipad is present the API should handle it.

![image](https://github.com/ansys/pyedb-core/assets/74993647/fe902d29-cfb2-4416-90af-9214b5804f7b)

### 📝 Steps to reproduce

from unittest 

   def test_set_all_antipad_values(self):
        """Set all anti-pads from all pad-stack definition to the given value."""
        source_path = os.path.join(local_path, "example_models", test_subfolder, "ANSYS-HSD_V1.aedb")
        target_path = os.path.join(self.local_scratch.path, "test_0120.aedb")
        self.local_scratch.copyfolder(source_path, target_path)
        edbapp = EdbGrpc(target_path, edbversion=desktop_version)
        assert edbapp.padstacks.set_all_antipad_value(0.0)
        edbapp.close()

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
pyedb-core
```

**Comment by drewm102** [comment] 2024-03-29 00:35
@svandenb-dev This was the intended behavior on our side in the sense that we thought the user would use a try/except block. In the scenario where the pad params aren't defined for that particular request, the exception thrown by the server would be caught and handled on the client side. Alternatively, we could return an empty tuple instead. Which behavior would you prefer?

**Comment by drewm102** [comment] 2024-10-10 19:40
@svandenb-dev I'm closing this for now since it is expected behavior as I described in my last comment. Feel free to reopen it if you feel that changes are necessary.

**Closed by drewm102** 2024-10-10 19:40 UTC
Labels: bug
